language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t neethubc910/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true neethubc910/docker-react npm run test
